fix: use next pagination across project
aeternity/mdw-frontend pull request #128
Opened 2021-12-01 20:59 UTC by thepiwo

2021-12-02 09:58 UTC, marc0olo commented
thanks @thepiwo!

@AtanasKrondev can you review this PR? it is supposed to address the upcoming mdw backend which dropped support for the page param.

I assume you can check by using `https://testnet.aeternity.art/mdw` as backend. the new version isn't deployed officially yet

2021-12-02 14:31 UTC, AtanasKrondev commented
``Load more`` on transactions page wasn't working when the type is ``All``.  And the use of objects on the same page to check if a transaction is already fetched seems redundant. @thepiwo @marc0olo  check my commits about this.
Also seems like that the transactions module in the store needs refactoring, as we are only calling actions without relying on the state, but that may be a different topic.

2021-12-02 14:34 UTC, marc0olo commented
the only way I can test it is clicking through the app and check about things not working. I will do that asap. will compare with current state of mdw which is deployed.

> Also seems like that the transactions module in the store needs refactoring, as we are only calling actions without relying on the state, but that may be a different topic.

is this about remembering the cursor which would allow to return to the correct position in overview when visiting a tx detailview?

2021-12-02 14:58 UTC, AtanasKrondev commented
I mean the vuex store. We are not using any state, we only use the actions to make the calls to the mdw. It's just an observation, I need to make a research if it'll be better to save the already fetched transactions in it... although due to the dynamic nature of the constantly updating transaction list probably it's not needed. Or would it be better to organise in a different way the data fetching.

2021-12-02 15:23 UTC, thepiwo commented on store/transactions.js
> +  getLatest: async function ({ state, rootGetters: { middleware }, commit }, { limit, page }) {
I don't fine where getLatest is called with page

2021-12-02 15:26 UTC, thepiwo commented
I tried to not include any other refactorings in here other than the hacky switch to use next page instead of page + 1. All this needs to be refactored to be more like some of the previously existing nextPage logic in store.

2021-12-03 11:18 UTC, AtanasKrondev approved these changes
For me the PR is good to go

2021-12-04 13:06 UTC, marc0olo commented
@thepiwo @AtanasKrondev this is intended to be used with `v1.3.0` of the middleware, right?

I am currently testing with following URLS:
```
    middlewareURL: process.env.NUXT_APP_NODE_URL || 'https://mainnet.test.aeternity.art/mdw',
    middlewareWS: process.env.NUXT_APP_NODE_WS || 'wss://mainnet.test.aeternity.art/mdw/websocket',
```

using these URLs I get an error on the dashboard, here the console log:
![image](https://user-images.githubusercontent.com/8124114/144710522-b5fd1844-52e7-493c-94a2-2f0bc0b15462.png)

2021-12-05 16:58 UTC, AtanasKrondev commented
Seems to work fine with the current mainnet version (no changes at all to the env)

2021-12-06 19:27 UTC, marc0olo commented
@AtanasKrondev today I tested again with the current mainnet version. I get the same error on the dashboard. can you please check and click around, go back to dashboard, etc.?

I can also provide a screencast. I see the latest generations loading and suddenly an error happens.

I am talking about dashboard view only

2021-12-08 10:33 UTC, marc0olo requested changes
explicitely requesting the changes just that we don't forget to fix. from my latest information Atanas also faced the issue on dashboard

2021-12-08 12:39 UTC, marc0olo approved these changes
looks good to me know. also works with `v1.3.1` of mdw backend ;-)

2021-12-08 12:39 UTC, merged