feat: the ability to sort names ASC/Desc (#61)
aeternity/mdw-frontend pull request #145
Opened 2022-01-17 10:38 UTC by ifaouibadi

2022-01-18 21:58 UTC, marc0olo requested changes
really cool in general! :-)

few things you should revisit:

- handling the the sorts correctly (probably also different logical sorting) given the state by the name (active, in auction, expired)
- display some labels meaningful depending on the state of the name
     - e.g. "expired at" instead of "expires at" (actually I am wondering if it is better right now to exclude expires names in that view to avoid confusion in general as we have a redesign in work anyway)
     - for auctions I am not sure what "Expiration height" stands for in the current UI. is it when the auction ends? then we should also adjust the labeling. actually as user I wanna know when the auction ends. maybe we can also calculate the estimated time based on the general 3 minutes average of an auction when comparing it to the height of the latest generation (aenalytics.org for example is doing that)

2022-01-19 06:41 UTC, ifaouibadi commented
Updated the expired at the field to display the diff in human format, and also the text (expires/expired) will be based on if the date is on future or past. 

![304EF86C-A3E1-49D5-85D1-D0FA7B47CDF6](https://user-images.githubusercontent.com/10424827/150077604-33af72f0-6f90-478d-9b57-1ec7879ef2ba.png)

2022-01-20 12:08 UTC, marc0olo approved these changes
![image](https://user-images.githubusercontent.com/8124114/150335764-2cb59ee5-2782-4fef-ad73-5c26c3dd30df.png)

@ifaouibadi let's rename `Expires at` to `Expiration Height`. then it is semantically correct for all name states.

let me know if you changed this. then we can merge =)

nice!

2022-01-20 12:21 UTC, marc0olo approved these changes

2022-01-20 12:21 UTC, merged